### ISSUE TITLE
on yazi 0.4.2 example doesn't work

### ISSUE THREAD

**Issue by pcause** [AnirudhG07/custom-shell.yazi#10]
I put this in my keystroke.yml

[[manager.prepend_keymap]]
on = [ "'", "3" ]
run = "plugin custom-shell --args='custom --wait zsh \"echo hi\" -o'"
desc = "Run echo hi"

which is from the examples.  it ran the command but didn't wait.  also, after hitting "3", I get a pop up that says:

zsh -ic 'echo hi;exit'

**Comment by AnirudhG07** [comment]
huh. strange, I just updated it with yazi0.4 updates like yest or something.
I'll look into this and get back to you!

**Comment by AnirudhG07** [comment]
Hi, I have fixed the issue. Also I think I have made a mistake in the argument order in the README. It will be fixed by tonight and willl close the issue then!

**Comment by pcause** [comment]
just tried and still not waiting.

**Comment by AnirudhG07** [comment]
yeah you have to change the position of `--wait`, it should be after the command, like `custom zsh \"ls\" -w` or similar. I was talking about this only to edit in readme. Ill try to possibly improve this situation too.

**Comment by pcause** [comment]
I have this:

run = "plugin custom-shell --args='custom  zsh \"echo hi\" --wait '" and also with a "-o" after the wait and neither work.

**Comment by pcause** [comment]
I have this:

run = "plugin custom-shell --args='custom  zsh \"echo hi\" --wait '" and also with a "-o" after the wait and neither work.

perhaps require that the last argument be the shell string to execute and that ALL of the options precede it.

**Comment by AnirudhG07** [comment]
yeah so backslash your `echo hi` otherwise quotation classes will happen.
Assuming you did that, I am trying here at my machine. it works just fine..., I have `run = 'plugin custom-shell --args="custom zsh \"echo hi\" -w -o"'`

**Comment by AnirudhG07** [comment]
If it doesnt work for you, dont worry. I'll make it work by tomorrow! ill take your reviews again.

**Comment by AnirudhG07** [comment]
Closing this issue in favour of #11, will be fixed very soon. Thanks for the notice! the plugin needs more changes based on yazi v0.4.x
