### ISSUE TITLE
README sample config typo

### ISSUE THREAD

**Issue by seattlelizzard** [AnirudhG07/custom-shell.yazi#8]
Hello,

In the readme sample config there is a period where there should be a colon, the lua provided says to use 

require("custom-shell").setup({
    history_path = "default",
    save_history = true,
})

When it should be

require("custom-shell"):setup({
    history_path = "default",
    save_history = true,
})

**Comment by AnirudhG07** [comment]
Oh yeah thanks. Didn't notice this.
Would you like to make a PR and correct it? Thanks

**Comment by seattlelizzard** [comment]
#9 Made one
